#Thu Oct 24 12:40:55 UTC 2024
micronaut:
  application:
    name: mqttdemo
mqtt:
  client:
    server-uri: tcp://${mqtt.host}:${mqtt.port}
    client-id: ${random.uuid}
test-resources:
  containers:
    mosquitto:
      image-name: eclipse-mosquitto
      hostnames:
        - mqtt.host
      exposed-ports:
        - mqtt.port: 1883
      ro-fs-bind:
        - "src/test/resources/mosquitto.conf": /mosquitto/config/mosquitto.conf